export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const CURRENT_USER_DETAIL = "CURRENT_USER_DETAIL";
export const UPDATE_USER = "UPDATE_USER";
export const VERIFY_RESET_PASSWORD_TOKEN = "VERIFY_RESET_PASSWORD_TOKEN";
export const SEND_PASSWORD_RESET_EMAIL = "SEND_PASSWORD_RESET_EMAIL";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const REQUEST_EMAIL_VERIFICATION_EMAIL = "REQUEST_EMAIL_VERIFICATION_EMAIL";
export const VERIFY_EMAIL_TOKEN = "VERIFY_EMAIL_TOKEN";

export const HIDE_MESSAGE = "HIDE_MESSAGE";
export const FLASH_MESSAGE = "FLASH_MESSAGE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";
